<?php
namespace app\admin\controller;
use think\Controller;
use think\Request;
class Index extends Common {
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\admin\model\Information();
    }
    public function index(){
        return $this->fetch();
    }
    public function Information(){
        $article=$this->db->getArticle();
        $this->assign('article',$article);
        return $this->fetch();
    }
    public function addInformation(Request $request){
        if($request->isPost()){
            $result=$this->db->addInformation(input('post.'));
            if($result['value']){
                $this->success($result['msg'],'index/information');exit;
            }else{
                $this->error($result['msg'],'index/addinformation');
            }
        }
        return $this->fetch();
    }
    public function EditInformation(Request $request){
        if($request->isPost()){
            $result=$this->db->updateInformation(input('post.'));
            if($result){
                $this->success('更新成功','index/information');
            }else{
                $this->error('更新失败');
            }
        }
        $article_id=input("id");
        $article=$this->db->editInformation($article_id);
        $this->assign('article',$article);
        return $this->fetch();
    }
    public function delInformation(Request $request){
        $information_id=input('id');
        $result=$this->db->delInformation($information_id);
        if($result){
            $this->success('删除成功','index/information');
        }else{
            $this->error('删除失败');
        }
    }
}