<?php

namespace app\admin\controller;

use think\Controller;

class Bis extends Controller
{
    private $obj;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('Bis');
    }

    /**
     * 入驻申请列表
     * @return mixed
     */
    public function apply(){
        $bis=$this->obj->getBisByStatus();
        $this->assign('bis',$bis);
        return $this->fetch();
    }
    public function detail(){
        $id=input('get.id');
        if(empty($id)){
            return $this->error('ID错误');
        }
//        $this->assign();
        $citys=model('City')->getNormalCitysByParentId();
        $categorys=model('Category')->getNormalCategorysByParentId();
        //获取商户数据
        $bisData=model('Bis')->get($id);
        $locationData=model('BisLocation')->get(['bis_id'=>$id,'is_main'=>1]);
        $accountData=model('BisAccount')->get(['bis_id'=>$id,'is_main'=>1]);
        $this->assign('citys',$citys);
        $this->assign('categorys',$categorys);
        $this->assign('bisData',$bisData);
        $this->assign('locationData',$locationData);
        $this->assign('accountData',$accountData);
        return $this->fetch();
    }
}